name: esp8266_controller
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mqtt_client: ^10.0.8
  file_picker: ^10.1.0
  fluttertoast: ^8.2.12
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.1.0
  permission_handler: ^12.0.0
  path_provider: ^2.1.5
  get: ^4.7.2
  # system_alert_window: ^2.0.4
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

